### ISSUE TITLE
Typo in Copyright header

### ISSUE THREAD

**Issue by abergerSRS** [thinkSRS/srsgui#5]
https://github.com/thinkSRS/srsgui/blob/00556493ec1d712110c602aea9ec7c79b15c89bf/srsgui/examples/oscilloscope%20example/instruments/cg635.py#L2C5-L2C14

This is a recurring typo in the boilerplate Copyright header that I see throughout the source code. I don't know if the boilerplate was auto-generated somewhere, or manually copied-and-pasted, but in many places it reads "Coptright" instead of "Copyright", and "All right reserved" instead of "All rights reserved"

Should read:
```
##! 
##! Copyright(c) 2022, 2023 Stanford Research Systems, All rights reserved
##! Subject to the MIT License
##! 
```

**Comment by srsrga** [comment]
Fixed.
