### ISSUE TITLE
Propose renaming tasks with descriptive names

### ISSUE THREAD

**Issue by abergerSRS** [thinkSRS/srsgui#6]
https://github.com/thinkSRS/srsgui/blob/00556493ec1d712110c602aea9ec7c79b15c89bf/srsgui/examples/oscilloscope%20example/oscilloscope%20example%20project.taskconfig#L34C1-L38C57

In the "Oscilloscope example" Project, I propose the following renaming (or similar):

```
task: *IDN test,                 tasks.identify,      Identify
task: Plot example,              tasks.plot_example,  PlotExample
task: Capture Osc. waveform,     tasks.scope_capture, ScopeCapture
task: FFT of captured waveform,  tasks.captured_fft,  CapturedFFT
task: FFT of simulated waveform, tasks.simulated_fft, SimulatedFFT
```

**Comment by srsrga** [comment]
Done.
